### ISSUE TITLE
core-icon: 3d-rotation vs. rotation-3d

### ISSUE THREAD

**Issue by a14n** [dart-lang/core-elements#191] opened 2015-02-05 13:42 UTC
In `core-elements-0.6.0+4` there's a `3d-rotation` icon in [the JS version](https://github.com/Polymer/core-icons/blob/7a8e6eeff629c0c2f3a7bd993193a00be41c5330/core-icons.html#L37) that is named `rotation-3d` in [the Dart version](https://github.com/dart-lang/core-elements/blob/670af438a70cf9f358976000d810b80f56772291/lib/src/core-icons/core-icons.html#L199). The [demo](https://www.polymer-project.org/components/core-icons/demo.html) shows only `3d-rotation`.

**Comment by jakemac53** [comment] 2015-02-05 17:03
My guess would be that this is just a version difference. The dart version of core-elements is a few versions behind right now.

**Comment by a14n** [comment] 2015-02-05 17:30
Right, the change appeared in `0.5.3`.

**Comment by jakemac53** [comment] 2015-02-05 17:31
ok, marking as dupe of https://github.com/dart-lang/core-elements/issues/188 then

**Closed by jakemac53** 2015-02-05 17:31 UTC
